"""This is an automatically generated stub for `toRL.capnp`."""

from __future__ import annotations

from contextlib import contextmanager
from io import BufferedWriter
from typing import Iterator

class Controls:
    throttle: float
    steer: float
    pitch: float
    yaw: float
    roll: float
    boost: bool
    jump: bool
    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes, traversal_limit_in_words: int | None = ..., nesting_limit: int | None = ...
    ) -> Iterator[ControlsReader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes, traversal_limit_in_words: int | None = ..., nesting_limit: int | None = ...
    ) -> ControlsReader: ...
    @staticmethod
    def new_message() -> ControlsBuilder: ...
    def to_dict(self) -> dict: ...

class ControlsReader(Controls):
    def as_builder(self) -> ControlsBuilder: ...

class ControlsBuilder(Controls):
    @staticmethod
    def from_dict(dictionary: dict) -> ControlsBuilder: ...
    def copy(self) -> ControlsBuilder: ...
    def to_bytes(self) -> bytes: ...
    def to_bytes_packed(self) -> bytes: ...
    def to_segments(self) -> list[bytes]: ...
    def as_reader(self) -> ControlsReader: ...
    @staticmethod
    def write(file: BufferedWriter) -> None: ...
    @staticmethod
    def write_packed(file: BufferedWriter) -> None: ...
