[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
  "src/mai"
]

# [tool.hatch.metadata]
# allow-direct-references = true

[project]
name="ModuleAI_Client"
version="0.1"
authors = [
    {name="Геворкян Артём", email="tima-1324@mail.ru"}
]
description = "Module RL AI for RL"
dependencies = [
    'torch',
    'pycapnp'
]
classifiers = [
    "Development Status :: 4 - Beta"
    , "Operating System :: POSIX :: Linux"
    , "Operating System :: Microsoft :: Windows"
    , "Programming Language :: Python"
    , "Programming Language :: Python :: 3"
    , "Programming Language :: Python :: 3 :: Only"
    , "Programming Language :: Python :: 3.11"
    , "Natural Language :: Russian"
]
requires-python = "> 3.9"

# [project.optional-dependencies]
#     md2gost = [
# ]

